### PR TITLE
update nmake files according to TIP 477

### PR DESCRIPTION
**Pull request by Kazmirchuk**
Also I've removed unused Windows-specific code

### CODE REVIEW

**Comment by gjrtimmer** [comment]
Any update on this?

**Comment by bovine** [comment]
Although possibly beyond the original scope of this PR, officially supporting Windows could be better done if we could add a GH Action to do CI builds against Windows.

**Review by resuna — APPROVED** [review]
Apart from some unnecessary tab/space conversion, which I don't really care about, this looks good to me.

**Comment by Kazmirchuk** [comment]
do you need anything more in order for this to be merged?

**Pull request merged**
